// SPDX-License-Identifier: GPL-3.0-only

#pragma once

#ifndef XMIPP4_CUDA_COALESCE_ALIGN_BYTES
	#define XMIPP4_CUDA_COALESCE_ALIGN_BYTES 256UL
#endif

#ifndef XMIPP4_CUDA_DEVICE_HEAP_STEP_BYTES
	#define XMIPP4_CUDA_DEVICE_HEAP_STEP_BYTES (2UL << 20)
#endif

#ifndef XMIPP4_CUDA_PINNED_HEAP_STEP_BYTES
	#define XMIPP4_CUDA_PINNED_HEAP_STEP_BYTES (1UL << 20)
#endif

#ifndef XMIPP4_CUDA_SMALL_QUEUE_COUNT
	#define XMIPP4_CUDA_SMALL_QUEUE_COUNT 4UL
#endif
