// SPDX-License-Identifier: GPL-3.0-only

#pragma once

#define REXLIB_CUDA_LOG_LEVEL_TRACE SPDLOG_LEVEL_TRACE
#define REXLIB_CUDA_LOG_LEVEL_DEBUG SPDLOG_LEVEL_DEBUG
#define REXLIB_CUDA_LOG_LEVEL_INFO SPDLOG_LEVEL_INFO
#define REXLIB_CUDA_LOG_LEVEL_WARN SPDLOG_LEVEL_WARN
#define REXLIB_CUDA_LOG_LEVEL_ERROR SPDLOG_LEVEL_ERROR
#define REXLIB_CUDA_LOG_LEVEL_CRITICAL SPDLOG_LEVEL_CRITICAL

#ifdef REXLIB_CUDA_LOG_LEVEL
	#define SPDLOG_ACTIVE_LEVEL REXLIB_CUDA_LOG_LEVEL
#endif

#include <spdlog/spdlog.h>

#define REXLIB_CUDA_LOG_TRACE(...) SPDLOG_TRACE(__VA_ARGS__)
#define REXLIB_CUDA_LOG_DEBUG(...) SPDLOG_DEBUG(__VA_ARGS__)
#define REXLIB_CUDA_LOG_INFO(...) SPDLOG_INFO(__VA_ARGS__)
#define REXLIB_CUDA_LOG_WARN(...) SPDLOG_WARN(__VA_ARGS__)
#define REXLIB_CUDA_LOG_ERROR(...) SPDLOG_ERROR(__VA_ARGS__)
#define REXLIB_CUDA_LOG_CRITICAL(...) SPDLOG_CRITICAL(__VA_ARGS__)
